name: GitHub Actions to AWS OIDC Deploy Phase 1

on:
  # manual trigger
  workflow_dispatch:
  # trigger on push to listed branches, uncomment to enable
  # push:
  #   branches:
  #     - main
  #     - lab3  # current branch, temporary

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./GitHubActionswithAWSOIDC/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (static key)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Deploy site to AWS S3
        run: |
          aws s3 sync ./examples/site s3://${{ secrets.S3_BUCKET }}/ --delete
